package com.sinodal.CardGeneratorVictorNicolauNeto.model;

import java.time.YearMonth;

public class CardValidator {

    public static boolean validar(Card card) {
        if (card == null) return false;
        // accept test cards generated by this app
        try {
            if (card.isTeste()) return true;
        } catch (Exception e) {
            // ignore - compatibility with older Card without the field
        }
        String num = card.getNumero();
        if (num == null || num.length() != 16) return false;
        if (card.getCvv() < 100 || card.getCvv() > 999) return false;
        if (card.getValidade() == null || !card.getValidade().isAfter(YearMonth.now())) return false;
        // check Luhn algorithm for plausible card numbers
        return luhnCheck(num);
    }

    private static boolean luhnCheck(String ccNumber) {
        int sum = 0;
        boolean alt = false;
        for (int i = ccNumber.length() - 1; i >= 0; i--) {
            int n = Integer.parseInt(ccNumber.substring(i, i + 1));
            if (alt) {
                n *= 2;
                if (n > 9) n = (n % 10) + 1;
            }
            sum += n;
            alt = !alt;
        }
        return (sum % 10 == 0);
    }
}
