services:
  - type: web
    name: cardgenerator
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/*.jar
    plan: free
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0
      - key: PORT
        generateValue: true