package com.sinodal.CardGeneratorVictorNicolauNeto.model;

import java.time.YearMonth;

public class CardValidator {

    public static boolean validar(Card card) {
        if (card == null) return false;
        
        // Validar nome do titular
        if (card.getNomeTitular() == null || card.getNomeTitular().trim().isEmpty()) {
            return false;
        }
        if (card.getNomeTitular().length() > 100) {
            return false;
        }
        
        // Validar bandeira
        if (card.getBandeira() == null || card.getBandeira().trim().isEmpty()) {
            return false;
        }
        
        // Accept test cards generated by this app
        try {
            if (card.isTeste()) return true;
        } catch (Exception e) {
            // ignore - compatibility with older Card without the field
        }
        
        // Validar número do cartão
        String num = card.getNumero();
        if (num == null) return false;
        if (!num.matches("\\d+")) return false; // Apenas dígitos
        
        // Validar comprimento baseado na bandeira
        int expectedLength = getExpectedLength(card.getBandeira());
        if (num.length() != expectedLength) return false;
        
        // Validar prefixo da bandeira
        if (!validarPrefixoBandeira(num, card.getBandeira())) return false;
        
        // Validar CVV
        if (card.getCvv() < 100 || card.getCvv() > 999) return false;
        
        // Validar validade
        if (card.getValidade() == null || !card.getValidade().isAfter(YearMonth.now())) {
            return false;
        }
        
        // Check Luhn algorithm for plausible card numbers
        return luhnCheck(num);
    }
    
    private static int getExpectedLength(String bandeira) {
        switch (bandeira) {
            case "American Express": return 15;
            case "Visa":
            case "MasterCard":
            case "Elo":
            case "Hipercard":
            default: return 16;
        }
    }

    private static boolean luhnCheck(String ccNumber) {
        int sum = 0;
        boolean doubleDigit = false;
        
        // Processa da direita para esquerda
        for (int i = ccNumber.length() - 1; i >= 0; i--) {
            int digit = Character.getNumericValue(ccNumber.charAt(i));
            
            if (doubleDigit) {
                digit *= 2;
                if (digit > 9) {
                    digit = (digit / 10) + (digit % 10);
                }
            }
            
            sum += digit;
            doubleDigit = !doubleDigit;
        }
        
        return (sum % 10 == 0);
    }
    
    public static boolean validarPrefixoBandeira(String numero, String bandeira) {
        if (numero == null || bandeira == null) return false;
        
        switch (bandeira) {
            case "Visa":
                return numero.startsWith("4") && numero.length() == 16;
            case "MasterCard":
                return ((numero.startsWith("51") || numero.startsWith("52") || 
                        numero.startsWith("53") || numero.startsWith("54") || 
                        numero.startsWith("55")) || 
                       (numero.length() >= 4 && Integer.parseInt(numero.substring(0, 4)) >= 2221 && 
                        Integer.parseInt(numero.substring(0, 4)) <= 2720)) && numero.length() == 16;
            case "American Express":
                return (numero.startsWith("34") || numero.startsWith("37")) && numero.length() == 15;
            case "Elo":
                return (numero.startsWith("4011") || numero.startsWith("4312") || 
                       numero.startsWith("4389") || numero.startsWith("4514") || 
                       numero.startsWith("4573") || numero.startsWith("5067") || 
                       numero.startsWith("5090") || numero.startsWith("6277") || 
                       numero.startsWith("6362") || numero.startsWith("6363") ||
                       numero.startsWith("636297") || numero.startsWith("636368") ||
                       numero.startsWith("438935")) && numero.length() == 16;
            case "Hipercard":
                return numero.startsWith("6062") && numero.length() == 16;
            default:
                return false;
        }
    }
}
